services:
  - type: web
    name: prudentcorp
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn prudent_proj.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: prudentcorp_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: MONO_PUBLIC_KEY
        sync: false
      - key: MONO_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
databases:
  - name: prudentcorp_db
    databaseName: prudentcorp
    plan: free